apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume
  namespace: prod
  labels:
    app: resume
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume
  template:
    metadata:
      labels:
        app: resume
    spec:
      containers:
      - name: resume
        image: 041825629273.dkr.ecr.us-east-1.amazonaws.com/griffinmahoney-com/resume:release-2ccb1d0
        imagePullPolicy: Always
        ports:
        - containerPort: 10100
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: HOSTNAME
          value: "0.0.0.0"
        - name: PORT
          value: "10100"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 10100
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 10100
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: resume
  namespace: prod
  labels:
    app: resume
spec:
  type: NodePort
  selector:
    app: resume
  ports:
  - port: 10100
    targetPort: 10100
    nodePort: 30100
    protocol: TCP
    name: http

